/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */

export interface Exercise {
  name: string;
  sets?: number;
  reps?: number;
  weight?: number | null;
  id: number;
  routine_id: number;
}
