/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */

export interface Payment {
  amount: number;
  payment_method: string;
  id: number;
  student_id: number;
  date: string;
}
