/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */

export interface RoutineCreate {
  day_of_week: number;
  name: string;
  student_id: number;
  coach_id: number;
}
