/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */
import type { Exercise } from './exercise';

export interface Routine {
  day_of_week: number;
  name: string;
  id: number;
  student_id: number;
  coach_id: number;
  exercises?: Exercise[];
}
