/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  email: string;
  name: string;
  is_coach?: boolean;
  id: number;
  created_at: string;
}
