/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */

export interface UserCreate {
  email: string;
  name: string;
  is_coach?: boolean;
  password: string;
}
