/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Gymbro API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  Payment,
  PaymentCreate,
  ReadPaymentsPaymentsGetParams,
  ReadUsersUsersGetParams,
  Routine,
  RoutineCreate,
  User,
  UserCreate
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createUserUsersPostResponse200 = {
  data: User
  status: 200
}

export type createUserUsersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createUserUsersPostResponseSuccess = (createUserUsersPostResponse200) & {
  headers: Headers;
};
export type createUserUsersPostResponseError = (createUserUsersPostResponse422) & {
  headers: Headers;
};

export type createUserUsersPostResponse = (createUserUsersPostResponseSuccess | createUserUsersPostResponseError)

export const getCreateUserUsersPostUrl = () => {




  return `/users/`
}

/**
 * @summary Create User
 */
export const createUserUsersPost = async (userCreate: UserCreate, options?: RequestInit): Promise<createUserUsersPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateUserUsersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(userCreate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createUserUsersPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserUsersPostResponse
}





export const getCreateUserUsersPostMutationKey = () => ['createUserUsersPost'] as const;

export const getCreateUserUsersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,CreateUserUsersPostMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,CreateUserUsersPostMutationVariables, TContext> => {

const mutationKey = getCreateUserUsersPostMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUserUsersPost>>, CreateUserUsersPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createUserUsersPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUserUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createUserUsersPost>>>
    export type CreateUserUsersPostMutationBody = UserCreate
    export type CreateUserUsersPostMutationError = HTTPValidationError
    export type CreateUserUsersPostMutationVariables = {data: UserCreate}

    /**
 * @summary Create User
 */
export const useCreateUserUsersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUserUsersPost>>, TError,CreateUserUsersPostMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUserUsersPost>>,
        TError,
        CreateUserUsersPostMutationVariables,
        TContext
      > => {
      return useMutation(getCreateUserUsersPostMutationOptions(options), queryClient);
    }
    export type readUsersUsersGetResponse200 = {
  data: User[]
  status: 200
}

export type readUsersUsersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readUsersUsersGetResponseSuccess = (readUsersUsersGetResponse200) & {
  headers: Headers;
};
export type readUsersUsersGetResponseError = (readUsersUsersGetResponse422) & {
  headers: Headers;
};

export type readUsersUsersGetResponse = (readUsersUsersGetResponseSuccess | readUsersUsersGetResponseError)

export const getReadUsersUsersGetUrl = (params?: ReadUsersUsersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/?${stringifiedParams}` : `/users/`
}

/**
 * @summary Read Users
 */
export const readUsersUsersGet = async (params?: ReadUsersUsersGetParams, options?: RequestInit): Promise<readUsersUsersGetResponse> => {

  const res = await fetch(getReadUsersUsersGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readUsersUsersGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readUsersUsersGetResponse
}





export const getReadUsersUsersGetQueryKey = (params?: ReadUsersUsersGetParams,) => {
    return [
    `/users/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadUsersUsersGetQueryOptions = <TData = Awaited<ReturnType<typeof readUsersUsersGet>>, TError = HTTPValidationError>(params?: ReadUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readUsersUsersGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadUsersUsersGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readUsersUsersGet>>> = ({ signal }) => readUsersUsersGet(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readUsersUsersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadUsersUsersGetQueryResult = NonNullable<Awaited<ReturnType<typeof readUsersUsersGet>>>
export type ReadUsersUsersGetQueryError = HTTPValidationError


export function useReadUsersUsersGet<TData = Awaited<ReturnType<typeof readUsersUsersGet>>, TError = HTTPValidationError>(
 params: undefined |  ReadUsersUsersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readUsersUsersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof readUsersUsersGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadUsersUsersGet<TData = Awaited<ReturnType<typeof readUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ReadUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readUsersUsersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof readUsersUsersGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadUsersUsersGet<TData = Awaited<ReturnType<typeof readUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ReadUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readUsersUsersGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Users
 */

export function useReadUsersUsersGet<TData = Awaited<ReturnType<typeof readUsersUsersGet>>, TError = HTTPValidationError>(
 params?: ReadUsersUsersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readUsersUsersGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadUsersUsersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createRoutineRoutinesPostResponse200 = {
  data: Routine
  status: 200
}

export type createRoutineRoutinesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createRoutineRoutinesPostResponseSuccess = (createRoutineRoutinesPostResponse200) & {
  headers: Headers;
};
export type createRoutineRoutinesPostResponseError = (createRoutineRoutinesPostResponse422) & {
  headers: Headers;
};

export type createRoutineRoutinesPostResponse = (createRoutineRoutinesPostResponseSuccess | createRoutineRoutinesPostResponseError)

export const getCreateRoutineRoutinesPostUrl = () => {




  return `/routines/`
}

/**
 * @summary Create Routine
 */
export const createRoutineRoutinesPost = async (routineCreate: RoutineCreate, options?: RequestInit): Promise<createRoutineRoutinesPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreateRoutineRoutinesPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(routineCreate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRoutineRoutinesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRoutineRoutinesPostResponse
}





export const getCreateRoutineRoutinesPostMutationKey = () => ['createRoutineRoutinesPost'] as const;

export const getCreateRoutineRoutinesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoutineRoutinesPost>>, TError,CreateRoutineRoutinesPostMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createRoutineRoutinesPost>>, TError,CreateRoutineRoutinesPostMutationVariables, TContext> => {

const mutationKey = getCreateRoutineRoutinesPostMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRoutineRoutinesPost>>, CreateRoutineRoutinesPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createRoutineRoutinesPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRoutineRoutinesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createRoutineRoutinesPost>>>
    export type CreateRoutineRoutinesPostMutationBody = RoutineCreate
    export type CreateRoutineRoutinesPostMutationError = HTTPValidationError
    export type CreateRoutineRoutinesPostMutationVariables = {data: RoutineCreate}

    /**
 * @summary Create Routine
 */
export const useCreateRoutineRoutinesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoutineRoutinesPost>>, TError,CreateRoutineRoutinesPostMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRoutineRoutinesPost>>,
        TError,
        CreateRoutineRoutinesPostMutationVariables,
        TContext
      > => {
      return useMutation(getCreateRoutineRoutinesPostMutationOptions(options), queryClient);
    }
    export type readRoutinesForStudentRoutinesStudentStudentIdGetResponse200 = {
  data: Routine[]
  status: 200
}

export type readRoutinesForStudentRoutinesStudentStudentIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readRoutinesForStudentRoutinesStudentStudentIdGetResponseSuccess = (readRoutinesForStudentRoutinesStudentStudentIdGetResponse200) & {
  headers: Headers;
};
export type readRoutinesForStudentRoutinesStudentStudentIdGetResponseError = (readRoutinesForStudentRoutinesStudentStudentIdGetResponse422) & {
  headers: Headers;
};

export type readRoutinesForStudentRoutinesStudentStudentIdGetResponse = (readRoutinesForStudentRoutinesStudentStudentIdGetResponseSuccess | readRoutinesForStudentRoutinesStudentStudentIdGetResponseError)

export const getReadRoutinesForStudentRoutinesStudentStudentIdGetUrl = (studentId: number,) => {




  return `/routines/student/${studentId}`
}

/**
 * @summary Read Routines For Student
 */
export const readRoutinesForStudentRoutinesStudentStudentIdGet = async (studentId: number, options?: RequestInit): Promise<readRoutinesForStudentRoutinesStudentStudentIdGetResponse> => {

  const res = await fetch(getReadRoutinesForStudentRoutinesStudentStudentIdGetUrl(studentId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readRoutinesForStudentRoutinesStudentStudentIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readRoutinesForStudentRoutinesStudentStudentIdGetResponse
}





export const getReadRoutinesForStudentRoutinesStudentStudentIdGetQueryKey = (studentId: number,) => {
    return [
    `/routines/student/${studentId}`
    ] as const;
    }


export const getReadRoutinesForStudentRoutinesStudentStudentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError = HTTPValidationError>(studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadRoutinesForStudentRoutinesStudentStudentIdGetQueryKey(studentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>> = ({ signal }) => readRoutinesForStudentRoutinesStudentStudentIdGet(studentId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: studentId !== null && studentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadRoutinesForStudentRoutinesStudentStudentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>>
export type ReadRoutinesForStudentRoutinesStudentStudentIdGetQueryError = HTTPValidationError


export function useReadRoutinesForStudentRoutinesStudentStudentIdGet<TData = Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError = HTTPValidationError>(
 studentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>,
          TError,
          Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadRoutinesForStudentRoutinesStudentStudentIdGet<TData = Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError = HTTPValidationError>(
 studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>,
          TError,
          Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadRoutinesForStudentRoutinesStudentStudentIdGet<TData = Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError = HTTPValidationError>(
 studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Routines For Student
 */

export function useReadRoutinesForStudentRoutinesStudentStudentIdGet<TData = Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError = HTTPValidationError>(
 studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readRoutinesForStudentRoutinesStudentStudentIdGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadRoutinesForStudentRoutinesStudentStudentIdGetQueryOptions(studentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createPaymentPaymentsPostResponse200 = {
  data: Payment
  status: 200
}

export type createPaymentPaymentsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createPaymentPaymentsPostResponseSuccess = (createPaymentPaymentsPostResponse200) & {
  headers: Headers;
};
export type createPaymentPaymentsPostResponseError = (createPaymentPaymentsPostResponse422) & {
  headers: Headers;
};

export type createPaymentPaymentsPostResponse = (createPaymentPaymentsPostResponseSuccess | createPaymentPaymentsPostResponseError)

export const getCreatePaymentPaymentsPostUrl = () => {




  return `/payments/`
}

/**
 * @summary Create Payment
 */
export const createPaymentPaymentsPost = async (paymentCreate: PaymentCreate, options?: RequestInit): Promise<createPaymentPaymentsPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getCreatePaymentPaymentsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(paymentCreate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPaymentPaymentsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPaymentPaymentsPostResponse
}





export const getCreatePaymentPaymentsPostMutationKey = () => ['createPaymentPaymentsPost'] as const;

export const getCreatePaymentPaymentsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPaymentPaymentsPost>>, TError,CreatePaymentPaymentsPostMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createPaymentPaymentsPost>>, TError,CreatePaymentPaymentsPostMutationVariables, TContext> => {

const mutationKey = getCreatePaymentPaymentsPostMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPaymentPaymentsPost>>, CreatePaymentPaymentsPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createPaymentPaymentsPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePaymentPaymentsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createPaymentPaymentsPost>>>
    export type CreatePaymentPaymentsPostMutationBody = PaymentCreate
    export type CreatePaymentPaymentsPostMutationError = HTTPValidationError
    export type CreatePaymentPaymentsPostMutationVariables = {data: PaymentCreate}

    /**
 * @summary Create Payment
 */
export const useCreatePaymentPaymentsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPaymentPaymentsPost>>, TError,CreatePaymentPaymentsPostMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPaymentPaymentsPost>>,
        TError,
        CreatePaymentPaymentsPostMutationVariables,
        TContext
      > => {
      return useMutation(getCreatePaymentPaymentsPostMutationOptions(options), queryClient);
    }
    export type readPaymentsPaymentsGetResponse200 = {
  data: Payment[]
  status: 200
}

export type readPaymentsPaymentsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readPaymentsPaymentsGetResponseSuccess = (readPaymentsPaymentsGetResponse200) & {
  headers: Headers;
};
export type readPaymentsPaymentsGetResponseError = (readPaymentsPaymentsGetResponse422) & {
  headers: Headers;
};

export type readPaymentsPaymentsGetResponse = (readPaymentsPaymentsGetResponseSuccess | readPaymentsPaymentsGetResponseError)

export const getReadPaymentsPaymentsGetUrl = (params?: ReadPaymentsPaymentsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/payments/?${stringifiedParams}` : `/payments/`
}

/**
 * @summary Read Payments
 */
export const readPaymentsPaymentsGet = async (params?: ReadPaymentsPaymentsGetParams, options?: RequestInit): Promise<readPaymentsPaymentsGetResponse> => {

  const res = await fetch(getReadPaymentsPaymentsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readPaymentsPaymentsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readPaymentsPaymentsGetResponse
}





export const getReadPaymentsPaymentsGetQueryKey = (params?: ReadPaymentsPaymentsGetParams,) => {
    return [
    `/payments/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadPaymentsPaymentsGetQueryOptions = <TData = Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError = HTTPValidationError>(params?: ReadPaymentsPaymentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadPaymentsPaymentsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>> = ({ signal }) => readPaymentsPaymentsGet(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadPaymentsPaymentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>>
export type ReadPaymentsPaymentsGetQueryError = HTTPValidationError


export function useReadPaymentsPaymentsGet<TData = Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError = HTTPValidationError>(
 params: undefined |  ReadPaymentsPaymentsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readPaymentsPaymentsGet>>,
          TError,
          Awaited<ReturnType<typeof readPaymentsPaymentsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadPaymentsPaymentsGet<TData = Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError = HTTPValidationError>(
 params?: ReadPaymentsPaymentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readPaymentsPaymentsGet>>,
          TError,
          Awaited<ReturnType<typeof readPaymentsPaymentsGet>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadPaymentsPaymentsGet<TData = Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError = HTTPValidationError>(
 params?: ReadPaymentsPaymentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Payments
 */

export function useReadPaymentsPaymentsGet<TData = Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError = HTTPValidationError>(
 params?: ReadPaymentsPaymentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readPaymentsPaymentsGet>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadPaymentsPaymentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






